### ISSUE TITLE
Add Fritzing schematics

### ISSUE THREAD

**Issue by an4cr0n** [TheBigBangTeam/Alohomora-3FA#50]

**Comment by Sonic0** [comment]
Oh yeah!! Work in progress Man

**Comment by Sonic0** [comment]
![alohomora-3fa_schematic_fritzing_bb](https://user-images.githubusercontent.com/16443598/34694375-220d2272-f4c7-11e7-9dca-0dca9d7e60bf.png)

until now i did this scheme

**Comment by Sonic0** [comment]
![alohomora-3fa_schematic_fritzing_bb](https://user-images.githubusercontent.com/16443598/34732292-22134942-f565-11e7-964f-47a0630231c6.png)

**Comment by Sonic0** [comment]
now on Alpha 3 version. Probably Will be a Beta version

**Comment by an4cr0n** [comment]
@Sonic0 should this be closed?

**Comment by Sonic0** [comment]
No, it isn't complete!

**Comment by Sonic0** [comment]
![alohomora-3fa_schematic_fritzing_bb](https://user-images.githubusercontent.com/16443598/34894736-cd7f0cf6-f7e2-11e7-89fd-ea596cd9eb60.png)
Maybe this a final revision for the prototype

**Comment by Sonic0** [comment]
Ok..... I did an error. I do another commit!! :)

**Comment by Sonic0** [comment]
Added diode for the return of the current on the other 5 volt boards, during the flash of firware

**Comment by Sonic0** [comment]
Closed #50
